Задание к разделу React vs HTML
danielvinogradov/junior-course-boilerplate pull request #1
Opened 2020-11-17 13:15 UTC by danielvinogradov

2020-11-17 13:22 UTC, vislogurov requested changes

2020-11-17 13:22 UTC, vislogurov commented on src/App.js
> +      <div className="container">
Тут прямо напрашивается `main`

2020-11-17 13:22 UTC, vislogurov commented on src/components/BaseHeadline/BaseHeadline.js
> +    return <h1>{this.props.headline}</h1>
Общепринятой практикой в таких случаях будет использование `children`. Это позволяет не завязываться на тип передаваемого контента и открывает возможности для использования Children API и техник по типу render-props.

2020-11-17 13:22 UTC, vislogurov commented on src/components/BaseList/BaseList.js
> +    } else if (params.maxItemsToShow < 1) {
Это хорошо, что ты предусматриваешь терминальные кейсы. Но они должны быть понятны также и с точки зрения UI/UX. Разве пользователю надо знать о `params.maxItemsToShow` или "каком-то" списке?

Тут нужно что-то вроде `Список товаров пуст` итд

2020-11-18 17:54 UTC, danielvinogradov commented on src/App.js
> +      <div className="container">
Справедливо, переделал

2020-11-18 17:55 UTC, danielvinogradov commented on src/components/BaseHeadline/BaseHeadline.js
> +    return <h1>{this.props.headline}</h1>
Тоже переделал. Как раз хотел спросить о возможности реализации похожей на `slots` во vue.js

2020-11-18 18:00 UTC, danielvinogradov commented on src/components/BaseList/BaseList.js
> +    } else if (params.maxItemsToShow < 1) {
Действительно, не подумал и перенес ошибки приложения, важные исключительно для разработки, в UI. 

Мне хотелось показывать `Список товаров пуст` только в случае, когда список действительно пуст. И у меня возникло несколько вариантов, в т.ч. :
1. добавить `.env` и показывать эту ошибку в ui только в режиме разработки (не очень удачная идея)
2. оставить ту же проверку, но вместо демонстрирования ошибки в ui выкидывать ошибку в консоль
3. написать тест, но я в тестах не силен и не уверен, что такое стоит тестировать

В итоге решил вынести этот параметр в `props`, добавить для него валидацию, дефолтное значение и документацию.

2020-11-19 06:21 UTC, vislogurov approved these changes

2020-11-19 10:34 UTC, merged